hi! link goBuiltins OneHue1
hi! link goConst OneHue3
hi! link goDeclType OneHue1
hi! link goDeclaration OneHue3
hi! link goField OneHue5
hi! link goFunctionCall OneHue2
hi! link goMethod OneHue1
hi! link goType OneHue62
hi! link goTypeName OneHue62
hi! link goTypeDecl OneHue3
hi! link goUnsignedInts OneHue1
hi! link goVar OneHue3
hi! link goVarDefs OneHue5
hi! link goVarAssign OneHue5