hi! link haskellDeclKeyword OneHue2
hi! link haskellType OneHue4
hi! link haskellWhere OneHue5
hi! link haskellImportKeywords OneHue2
hi! link haskellOperators OneHue5
hi! link haskellDelimiter OneHue2
hi! link haskellIdentifier OneHue6
hi! link haskellKeyword OneHue5
hi! link haskellNumber OneHue1
hi! link haskellString OneHue1