hi! link htmlArg OneHue6
hi! link htmlH1 OneHue5
hi! link htmlH2 OneHue5
hi! link htmlH3 OneHue5
hi! link htmlH4 OneHue5
hi! link htmlH5 OneHue5
hi! link htmlH6 OneHue5
hi! link htmlSpecialChar OneHue6
hi! link htmlSpecialTagName OneHue5
hi! link htmlTag OneMono2
hi! link htmlTagN OneHue5
hi! link htmlEndTag OneMono2
hi! link htmlTagName OneHue5
hi! link htmlTagN OneHue5
hi! link htmlTitle OneMono1