hi! link perlFiledescRead OneHue4
hi! link perlFunction OneHue3
hi! link perlMatchStartEnd OneHue2
hi! link perlMethod OneHue3
hi! link perlPOD OneMono3
hi! link perlSharpBang OneMono3
hi! link perlSpecialString OneHue1
hi! link perlStatementFiledesc OneHue5
hi! link perlStatementFlow OneHue5
hi! link perlStatementInclude OneHue3
hi! link perlStatementScalar OneHue3
hi! link perlStatementStorage OneMono3
hi! link perlSubName OneHue62
hi! link perlVarPlain OneHue2