hi! link pythonImport OneHue3
hi! link pythonBuiltin OneHue1
hi! link pythonStatement OneHue3
hi! link pythonParam OneHue6
hi! link pythonEscape OneHue5
hi! link pythonClass OneHue2
hi! link pythonOperator OneHue3
hi! link pythonEscape OneHue5
hi! link pythonFunction OneHue2
hi! link pythonKeyword OneHue2
hi! link pythonModule OneHue3
hi! link pythonStringDelimiter OneHue4
hi! link pythonSymbol OneHue1