hi! link texStatement OneHue3
hi! link texSubscripts OneHue6
hi! link texSuperscripts OneHue6
hi! link texTodo OneHue52
hi! link texBeginEnd OneHue3
hi! link texBeginEndName OneHue2
hi! link texMathMatcher OneHue2
hi! link texMathDelim OneHue2
hi! link texDelimiter OneHue6
hi! link texSpecialChar OneHue6
hi! link texCite OneHue2
hi! link texRefZone OneHue2