hi! link zshCommands OneSyntaxFg
hi! link zshDeref OneHue5
hi! link zshShortDeref OneHue5
hi! link zshFunction OneHue1
hi! link zshKeyword OneHue3
hi! link zshSubst OneHue5
hi! link zshSubstDelim OneMono3
hi! link zshTypes OneHue3
hi! link zshVariableDef OneHue6